'use client';

import { type FormEvent, useEffect, useState } from 'react';
import { EmptyState, LoadingState, Notice, PageHeader, StatusBadge, formatDate } from '@/components/admin-ui';
import { apiRequest } from '@/lib/auth-api';

interface Trip { id: string; code: string; site_name: string; site_address: string; start_at: string; end_at: string; content: string; status: string; customerName?: string; memberCount: number; memberNames: string; }
interface Customer { id: string; name: string; address: string; }
interface Employee { id: string; employeeCode: string; fullName: string; isActive: boolean; }
const nextStatus: Record<string, string[]> = { DRAFT: ['ASSIGNED', 'CANCELLED'], ASSIGNED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'CANCELLED'] };

export default function BusinessTripsPage() {
  const [trips, setTrips] = useState<Trip[] | null>(null); const [customers, setCustomers] = useState<Customer[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function load(): Promise<void> { const [t, c, e] = await Promise.all([apiRequest<Trip[]>('/business-trips'), apiRequest<Customer[]>('/business-trips/lookups/customers'), apiRequest<Employee[]>('/employees')]); setTrips(t); setCustomers(c); setEmployees(e); }
  useEffect(() => { Promise.all([apiRequest<Trip[]>('/business-trips'), apiRequest<Customer[]>('/business-trips/lookups/customers'), apiRequest<Employee[]>('/employees')]).then(([t, c, e]) => { setTrips(t); setCustomers(c); setEmployees(e); }).catch(() => setError('Không thể tải phiếu công tác.')); }, []);
  async function createTrip(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiRequest('/business-trips', { method: 'POST', body: JSON.stringify({ code: form.get('code'), customerId: form.get('customerId') || undefined, siteName: form.get('siteName'), siteAddress: form.get('siteAddress'), startAt: form.get('startAt'), endAt: form.get('endAt'), content: form.get('content'), requiresPhoto: form.get('requiresPhoto') === 'on', memberIds: form.getAll('memberIds') }) }); event.currentTarget.reset(); setMessage('Đã tạo phiếu nháp.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể tạo phiếu.'); } }
  async function transition(id: string, status: string): Promise<void> { try { await apiRequest(`/business-trips/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); setMessage(`Đã chuyển phiếu sang ${status}.`); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể chuyển trạng thái.'); } }
  async function createCustomer(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiRequest('/business-trips/lookups/customers', { method: 'POST', body: JSON.stringify({ name: form.get('name'), address: form.get('address'), contactName: form.get('contactName') || undefined, contactPhone: form.get('contactPhone') || undefined }) }); event.currentTarget.reset(); setMessage('Đã thêm khách hàng.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể thêm khách hàng.'); } }
  return <div className="module-page"><PageHeader eyebrow="W5 / CÔNG TÁC" title="Phiếu công tác" description="Quản lý khách hàng, địa điểm, thành viên và state machine công tác." />{message && <Notice kind="success">{message}</Notice>}{error && <Notice kind="error">{error}</Notice>}
    <details className="editor-panel" open><summary>Tạo phiếu công tác</summary><form className="form-grid" onSubmit={createTrip}><label>Mã phiếu<input name="code" required /></label><label>Khách hàng<select name="customerId"><option value="">Không chọn</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tên địa điểm<input name="siteName" required /></label><label className="span-2">Địa chỉ<input name="siteAddress" required /></label><label>Bắt đầu<input name="startAt" type="datetime-local" required /></label><label>Kết thúc<input name="endAt" type="datetime-local" required /></label><label className="span-2">Nội dung<textarea name="content" required /></label><fieldset className="span-2 check-list"><legend>Thành viên</legend>{employees.filter((e) => e.isActive).map((e) => <label key={e.id}><input name="memberIds" type="checkbox" value={e.id} />{e.employeeCode} · {e.fullName}</label>)}</fieldset><label className="check-inline"><input name="requiresPhoto" type="checkbox" />Yêu cầu ảnh hiện trường</label><button className="primary-button form-action">Tạo phiếu nháp</button></form></details>
    <details className="editor-panel"><summary>Thêm khách hàng / phòng khám</summary><form className="inline-form customer-form" onSubmit={createCustomer}><input name="name" placeholder="Tên khách hàng" required /><input name="address" placeholder="Địa chỉ" required /><input name="contactName" placeholder="Người liên hệ" /><input name="contactPhone" placeholder="Điện thoại" /><button className="secondary-button">Thêm khách hàng</button></form></details>
    {trips === null ? <LoadingState /> : trips.length === 0 ? <EmptyState title="Chưa có phiếu công tác" description="Tạo phiếu mới và giao cho ít nhất một thành viên." /> : <div className="card-list">{trips.map((trip) => <article className="list-card trip-card" key={trip.id}><div><p className="mono">{trip.code}</p><h3>{trip.site_name}</h3><p>{trip.customerName ?? 'Không có khách hàng'} · {trip.memberNames}</p><small>{formatDate(trip.start_at)} → {formatDate(trip.end_at)}</small></div><div><StatusBadge value={trip.status} />{nextStatus[trip.status]?.map((status) => <button className="table-action" key={status} onClick={() => void transition(trip.id, status)}>{status}</button>)}</div></article>)}</div>}
  </div>;
}
